### ISSUE TITLE
Hi. After 24h i don't get any reward.

### ISSUE THREAD

**Issue by theca** [mkmatr/mkmatminer#3]
HI, after mining 24 hour i don't get any rewards. 
My config is:
- win 10
- nvidia GTX 1050 
- Use shard 2
- I write my directory node2.jsonon runibat.
 Maybe is my config. anyone get rewards? can you help me?

**Comment by ozl** [comment]
still the same? i have been 6 hours today and nothing

**Comment by mkmatr** [comment]
> HI, after mining 24 hour i don't get any rewards.
> My config is:
> 
> * win 10
> * nvidia GTX 1050
> * Use shard 2
> * I write my directory node2.jsonon runibat.
>   Maybe is my config. anyone get rewards? can you help me?

Did you contact me at telegram? If that's the case, it has been resolved

**Comment by mkmatr** [comment]
> still the same? i have been 6 hours today and nothing

What graphics card do you use? if there is still no reward, you can contact me on the telegram

**Comment by theca** [comment]
it's me on telegram :)
